#!/bin/bash

# Install dependencies
dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
dnf install -y curl make git @development-tools gcc-c++ cmake avahi-compat-libdns_sd-devel libplist-devel openssl-devel gstreamer1-plugins-base-devel gstreamer1-libav gstreamer1-vaapi gstreamer1-plugins-bad-free patchelf zlib-devel upx scons python3 python3-devel python3-pip
pip3 install staticx

# Fix certificate authorities on armv7
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Clone upstream
rm -rf /data/upstream
mkdir -p /data/upstream
git clone https://github.com/FD-/RPiPlay.git /data/upstream

# Build upstream (see https://github.com/FD-/RPiPlay#ubuntu-1804-or-2004)
cd /data/upstream
mkdir -p build
cd build
cmake ..
make

# Create static binary
staticx rpiplay rpiplay.static

# Copy binaries to staging directory
mkdir -p /data/staging
cp rpiplay /data/staging/rpiplay-linux.fedora.$(uname -m)
cp rpiplay.static /data/staging/rpiplay-linux.fedora.static.$(uname -m)
