#!/bin/bash

# Install dependencies
apt update
apt install -y curl make git build-essential cmake libavahi-compat-libdnssd-dev libplist-dev libssl-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-libav gstreamer1.0-vaapi gstreamer1.0-plugins-bad patchelf zlib1g-dev upx scons python3 python3-dev python3-pip
pip3 install staticx

# Fix certificate authorities on armv7
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Clone upstream
rm -rf /data/upstream
mkdir -p /data/upstream
git clone https://github.com/FD-/RPiPlay.git /data/upstream

# Build upstream (see https://github.com/FD-/RPiPlay#ubuntu-1804-or-2004)
cd /data/upstream
mkdir -p build
cd build
cmake ..
make

# Create static binary
staticx rpiplay rpiplay.static

# Copy binaries to staging directory
mkdir -p /data/staging
cp rpiplay /data/staging/rpiplay-linux.debian.$(uname -m)
cp rpiplay.static /data/staging/rpiplay-linux.debian.static.$(uname -m)
